
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CADENA = 10;
  public static final int DECIMAL = 16;
  public static final int LLAV_IZQ = 5;
  public static final int PUNTO = 8;
  public static final int PAR_IZQ = 3;
  public static final int LLAV_DER = 6;
  public static final int ENTERO = 15;
  public static final int POR = 7;
  public static final int PTCOMA = 2;
  public static final int ER = 13;
  public static final int EOF = 0;
  public static final int PAR_DER = 4;
  public static final int PORCENTAJE = 14;
  public static final int ID = 9;
  public static final int IGUAL = 11;
  public static final int error = 1;
  public static final int OR = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PTCOMA",
  "PAR_IZQ",
  "PAR_DER",
  "LLAV_IZQ",
  "LLAV_DER",
  "POR",
  "PUNTO",
  "ID",
  "CADENA",
  "IGUAL",
  "OR",
  "ER",
  "PORCENTAJE",
  "ENTERO",
  "DECIMAL"
  };
}

