
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int COMILLA_SIMPLE = 21;
  public static final int GUION = 7;
  public static final int CADENA = 28;
  public static final int CONCATENACION = 15;
  public static final int DOSPUNTOS = 11;
  public static final int OR = 16;
  public static final int IGUAL = 14;
  public static final int LETRA = 26;
  public static final int DECIMAL = 25;
  public static final int POSITIVA = 18;
  public static final int MAYOR_QUE = 8;
  public static final int LLAV_IZQ = 5;
  public static final int DPORCENTAJE = 12;
  public static final int ID = 27;
  public static final int LLAV_DER = 6;
  public static final int KLEENE = 17;
  public static final int COMA = 10;
  public static final int RW_CONJ = 2;
  public static final int COMILLA_DOBLE = 22;
  public static final int EOF = 0;
  public static final int PAR_IZQ = 3;
  public static final int error = 1;
  public static final int PAR_DER = 4;
  public static final int OPCIONAL = 19;
  public static final int SALTO_LINEA = 20;
  public static final int VIRGULILLA = 13;
  public static final int ASCII = 23;
  public static final int ENTERO = 24;
  public static final int PTCOMA = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "RW_CONJ",
  "PAR_IZQ",
  "PAR_DER",
  "LLAV_IZQ",
  "LLAV_DER",
  "GUION",
  "MAYOR_QUE",
  "PTCOMA",
  "COMA",
  "DOSPUNTOS",
  "DPORCENTAJE",
  "VIRGULILLA",
  "IGUAL",
  "CONCATENACION",
  "OR",
  "KLEENE",
  "POSITIVA",
  "OPCIONAL",
  "SALTO_LINEA",
  "COMILLA_SIMPLE",
  "COMILLA_DOBLE",
  "ASCII",
  "ENTERO",
  "DECIMAL",
  "LETRA",
  "ID",
  "CADENA"
  };
}

